prooph_event_store:
    stores:
        gamescore_store:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore
            repositories:
                game_list:
                    repository_class: Football\Gamescore\Infrastructure\Repository\EventStoreGameList
                    aggregate_type: Football\Gamescore\Domain\Aggregate\Game
                    aggregate_translator: prooph_event_sourcing.aggregate_translator
    projection_managers:
        game_projection_manager:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore
            connection: 'doctrine.pdo.connection'
            projections:
                game_projection:
                    read_model: Football\Gamescore\Projection\Game\GameReadModel
                    projection: Football\Gamescore\Projection\Game\GameProjection


services:
    Prooph\EventStore\Pdo\MySqlEventStore:
        arguments:
          - '@prooph_event_store.message_factory'
          - '@doctrine.pdo.connection'
          - '@prooph_event_store.single_stream_strategy'

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator