command::start-game:
    path: /api/game
    defaults: { _controller: Football\Gamescore\UserInterface\Controller\ApiCommandController:postAction, prooph_command_name: 'Football\Gamescore\Application\Command\StartGame' }

