# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Football\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Football\Gamescore\UserInterface\Controller\:
        resource: '../src/Gamescore/UserInterface/Controller'
        tags: ['controller.service_arguments']

    Football\Gamescore\UserInterface\Controller\ApiCommandController:
        class: Football\Gamescore\UserInterface\Controller\ApiCommandController
        arguments: ['@prooph_service_bus.gamescoring_command_bus', '@prooph_service_bus.message_factory']
        tags: ['controller.service_arguments']

    Football\Gamescore\Domain\Service\Game\SimpleLineupPolicy:
      class: Football\Gamescore\Domain\Service\Game\SimpleLineupPolicy

    Football\Gamescore\Application\Command\StartGameHandler:
        class: Football\Gamescore\Application\CommandHandler\StartGameHandler
        public: true
        arguments:
          - '@Football\Gamescore\Domain\Service\Game\SimpleLineupPolicy'
          - '@game_list'
        tags:
            - { name: 'prooph_service_bus.gamescoring_command_bus.route_target', message_detection: true }

    Football\Gamescore\Application\Command\ScoreGoalHandler:
        class: Football\Gamescore\Application\CommandHandler\ScoreGoalHandler
        public: true
        arguments:
          - '@game_list'
        tags:
            - { name: 'prooph_service_bus.gamescoring_command_bus.route_target', message_detection: true }